name: integration
on:
  push:
    branches:
    - master
    - integration-testing
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v1
    - name: install
      run: |
        GOBIN=$HOME/bin make install
        brew install mercurial fossil bazaar darcs
        curl -fsSL --compressed https://git.io/cpm > cpm
        chmod +x cpm
        /usr/bin/perl ./cpm install -L /usr/local/Cellar/git/2.26.2/share/perl5 SVN::Core
    - name: test
      run: PATH=$HOME/bin:$PATH ./misc/author/integration_test.sh
